Book detail
wolox-training/ts-angular pull request #22
Opened 2019-03-27 15:08 UTC by tomas-schmidt

## Summary

- Add frontend-bootstrap
- Add book detail screen

## Screenshots

![image](https://user-images.githubusercontent.com/19355122/55087517-02d89200-5089-11e9-86bf-a0409c206398.png)

## Trello Card

https://trello.com/c/gwnjvZQQ/17-book-detail

2019-03-28 17:55 UTC, FrankIglesias requested changes

2019-03-28 17:55 UTC, FrankIglesias commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.controller.js
> +    this.book = {
books?

2019-03-28 17:55 UTC, FrankIglesias commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.pug
> +      span.book-title {{bookDetailCtrl.book.title}}
```jade 
span.book-title
  | ... 
```

2019-03-28 17:55 UTC, FrankIglesias commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.scss
> +      height: $book-img-height;
set only one value.

2019-03-28 17:55 UTC, FrankIglesias commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.scss
> +      width: $book-img-width;
same

2019-03-28 17:55 UTC, FrankIglesias commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.scss
> +        width: 120px;
same

2019-03-29 14:27 UTC, tomas-schmidt commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.controller.js
> +    this.book = {
I'm mocking book detail response

2019-04-01 10:02 UTC, FrankIglesias requested changes

2019-04-01 10:02 UTC, FrankIglesias commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.pug
> +      span.book-desc Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ul
Piped text is recommended for long texts

2019-04-01 10:02 UTC, FrankIglesias commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.pug
> +        .book-img(ng-if='!book.image_url')
do you really need this div? why not just switch the src value

2019-04-01 10:02 UTC, FrankIglesias commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.scss
> +        width: $sugg-book-width;
At least add object fit property

2019-04-01 13:34 UTC, tomas-schmidt commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.controller.js
> +      // image_url: 'http://wolox-training.s3.amazonaws.com/uploads/6963511-M.jpg',
I'm just using this constant to mock the API response. It will be replaced with a service call and a handler, not contemplated on this card.

2019-04-01 13:34 UTC, tomas-schmidt commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.controller.js
> +      image_url: null,
same

2019-04-01 13:34 UTC, tomas-schmidt commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.controller.js
> +    this.book = {
same

2019-04-08 19:40 UTC, FrankIglesias requested changes

2019-04-08 19:40 UTC, FrankIglesias commented on wolox-books-angularjs/src/app/components/centered/book-detail/book-detail.scss
> +  width: $user-image-size;
add object-fit value

2019-04-09 19:40 UTC, FrankIglesias approved these changes

2019-04-10 12:54 UTC, merged